/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeMX
 * @brief     System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the newlib libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>
#include "FreeRTOS.h"
#include "task.h"
#include "common.h"


#if 1
/**
 * Pointer to the current high watermark of the heap usage
 */
static uint8_t *__sbrk_heap_end = NULL;

/**
 * @brief _sbrk() allocates memory to the newlib heap and is used by malloc
 *        and others from the C library
 *
 * @verbatim
 * ############################################################################
 * #  .data  #  .bss  #       newlib heap       #          MSP stack          #
 * #         #        #                         # Reserved by _Min_Stack_Size #
 * ############################################################################
 * ^-- RAM start      ^-- _end                             _estack, RAM end --^
 * @endverbatim
 *
 * This implementation starts allocating at the '_end' linker symbol
 * The '_Min_Stack_Size' linker symbol reserves a memory for the MSP stack
 * The implementation considers '_estack' linker symbol to be RAM end
 * NOTE: If the MSP stack, at any point during execution, grows larger than the
 * reserved size, please increase the '_Min_Stack_Size'.
 *
 * @param incr Memory size
 * @return Pointer to allocated memory
 */
void *_sbrk(ptrdiff_t incr)
{
  extern uint8_t _end; /* Symbol defined in the linker script */
  extern uint8_t _estack; /* Symbol defined in the linker script */
  extern uint32_t _Min_Stack_Size; /* Symbol defined in the linker script */
  const uint32_t stack_limit = (uint32_t)&_estack - (uint32_t)&_Min_Stack_Size;
  const uint8_t *max_heap = (uint8_t *)stack_limit;
  uint8_t *prev_heap_end;

  /* Initialize heap end at first call */
  if (NULL == __sbrk_heap_end)
  {
    __sbrk_heap_end = &_end;
  }

  /* Protect heap from growing into the reserved MSP stack */
  if (__sbrk_heap_end + incr > max_heap)
  {
    errno = ENOMEM;
    return (void *)-1;
  }

    prev_heap_end = __sbrk_heap_end;
    __sbrk_heap_end += incr;

  return (void *)prev_heap_end;
}

// 实现newlib的线程安全malloc锁定和解锁钩子函数
// 这些函数用于在多线程环境中保护malloc的内部状态，防止数据竞争
// FreeRTOS的任务调度器提供了临界区的进入和退出函数
void __malloc_lock(struct _reent *reent)
{
    CHECKPOINTB("malloc lock called!");
    taskENTER_CRITICAL();
}

void __malloc_unlock(struct _reent *reent)
{
    CHECKPOINTB("malloc unlock called!");
    taskEXIT_CRITICAL();
}

#else

void *malloc(size_t size) 
{
    CHECKPOINTA("malloc(%d) called!", size);
    return pvPortMalloc(size);
}

void free( void *pv )
{
   CHECKPOINTA("free(%x) called!", pv);
   vPortFree(pv);
}

void *calloc(size_t nmemb, size_t size)
{
    void *ptr = pvPortMalloc(nmemb * size);
    if (ptr) {
        memset(ptr, 0, nmemb * size);
    }
    CHECKPOINTA("calloc(%d, %d) called!", nmemb, size);
    return ptr;
}

void *realloc(void *ptr, size_t size)
{
    if (ptr == NULL) {
        CHECKPOINTA("realloc(NULL, %d) called!", size);
        return pvPortMalloc(size);
    }
    if (size == 0) {
        CHECKPOINTA("realloc(%x, 0) called!", ptr);
        vPortFree(ptr);
        return NULL;
    }
    // 获取原分配块大小无法直接实现，简单做法：分配新块，拷贝，释放旧块
    void *new_ptr = pvPortMalloc(size);
    if (new_ptr && ptr) {
        // 注意：这里无法获取原大小，只能假设用户自己保证安全
        memcpy(new_ptr, ptr, size); // 有风险，如果原ptr比新size大，会导致数据丢失；如果原ptr比新size小，可能会导致内存越界
    }
    vPortFree(ptr);
    CHECKPOINTA("realloc(%x, %d) called!", ptr, size);
    return new_ptr;
}

#endif